Repository AY2324S1-CS2103T-F08-1/tp, pull requests merged in 2023-11, with the labels that each got.

#106 Implement Prescription Class
  docs/diagrams/AddAppointmentSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/cc/logic/commands/appointmentcommands/AddPrescriptionCommand.java
  src/main/java/seedu/cc/logic/commands/appointmentcommands/DeletePrescriptionCommand.java
  src/main/java/seedu/cc/logic/commands/appointmentcommands/EditAppointmentEventCommand.java
  src/main/java/seedu/cc/logic/parser/CliSyntax.java
  src/main/java/seedu/cc/logic/parser/ClinicBookParser.java
  src/main/java/seedu/cc/logic/parser/ParserUtil.java
  src/main/java/seedu/cc/logic/parser/appointment/AddPrescriptionCommandParser.java
  src/main/java/seedu/cc/logic/parser/appointment/DeletePrescriptionCommandParser.java
  src/main/java/seedu/cc/model/ClinicBook.java
  src/main/java/seedu/cc/model/Model.java
  src/main/java/seedu/cc/model/ModelManager.java
  src/main/java/seedu/cc/model/appointment/AppointmentEvent.java
  src/main/java/seedu/cc/model/appointment/Prescription.java
  src/main/java/seedu/cc/model/patient/Patient.java
  src/main/java/seedu/cc/model/patient/UniquePatientList.java
  src/main/java/seedu/cc/model/util/Date.java
  src/main/java/seedu/cc/storage/JsonAdaptedAppointmentEvent.java
  src/main/java/seedu/cc/storage/JsonAdaptedPrescription.java
  src/main/java/seedu/cc/storage/JsonClinicBookStorage.java
  src/main/java/seedu/cc/storage/StorageManager.java
  src/test/java/seedu/cc/logic/commands/AddCommandTest.java
Labels: type.Task

#108 Rename Address to Age
  src/main/java/seedu/cc/MainApp.java
  src/main/java/seedu/cc/logic/Logic.java
  src/main/java/seedu/cc/logic/Messages.java
  src/main/java/seedu/cc/logic/commands/AddCommand.java
  src/main/java/seedu/cc/logic/commands/ClearCommand.java
  src/main/java/seedu/cc/logic/commands/EditCommand.java
  src/main/java/seedu/cc/logic/commands/FindCommand.java
  src/main/java/seedu/cc/logic/commands/ListCommand.java
  src/main/java/seedu/cc/logic/commands/appointmentcommands/AddAppointmentEventCommand.java
  src/main/java/seedu/cc/logic/parser/AddCommandParser.java
  src/main/java/seedu/cc/logic/parser/CliSyntax.java
  src/main/java/seedu/cc/logic/parser/EditCommandParser.java
  src/main/java/seedu/cc/logic/parser/ParserUtil.java
  src/main/java/seedu/cc/model/ClinicBook.java
  src/main/java/seedu/cc/model/Model.java
  src/main/java/seedu/cc/model/patient/Patient.java
  src/main/java/seedu/cc/model/person/Address.java
  src/main/java/seedu/cc/model/person/Age.java
  src/main/java/seedu/cc/model/person/Person.java
  src/main/java/seedu/cc/model/util/SampleDataUtil.java
  src/main/java/seedu/cc/storage/JsonAdaptedAppointmentEvent.java
  src/main/java/seedu/cc/storage/JsonAdaptedPatient.java
  src/main/java/seedu/cc/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonSerializableClinicBookTest/duplicatePersonClinicBook.json
  src/test/data/JsonSerializableClinicBookTest/typicalPatientClinicBook.json
  src/test/java/seedu/cc/logic/LogicManagerTest.java
  src/test/java/seedu/cc/logic/commands/CommandTestUtil.java
  src/test/java/seedu/cc/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/cc/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/cc/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/cc/logic/parser/ParserUtilTest.java
  src/test/java/seedu/cc/model/ClinicBookTest.java
  src/test/java/seedu/cc/model/patient/PatientTest.java
  src/test/java/seedu/cc/model/person/AddressTest.java
  src/test/java/seedu/cc/model/person/AgeTest.java
  src/test/java/seedu/cc/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/cc/model/person/PersonTest.java
  src/test/java/seedu/cc/model/person/UniquePersonListTest.java
  src/test/java/seedu/cc/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/cc/storage/StorageManagerTest.java
  src/test/java/seedu/cc/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/cc/testutil/PatientBuilder.java
  src/test/java/seedu/cc/testutil/PatientUtil.java
  src/test/java/seedu/cc/testutil/TypicalPatients.java
Labels: type.Task

#117 Add multiple prescription
  src/main/java/seedu/cc/logic/commands/appointmentcommands/DeletePrescriptionCommand.java
  src/main/java/seedu/cc/storage/JsonAdaptedAppointmentEvent.java
Labels: type.Task

#119 Update AddPrescriptionCommandParser.java
  src/main/java/seedu/cc/logic/parser/appointment/AddPrescriptionCommandParser.java
Labels: type.Task

#128 Branch user guide
  docs/UserGuide.md
Labels: type.documentation

#178 Branch fix
  docs/Gemfile
  docs/UserGuide.md
  src/main/java/seedu/cc/logic/commands/AddCommand.java
  src/main/java/seedu/cc/model/person/Phone.java
  src/test/data/JsonSerializableClinicBookTest/typicalPatientClinicBook.json
  src/test/java/seedu/cc/logic/parser/ParserUtilTest.java
  src/test/java/seedu/cc/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/cc/model/person/PhoneTest.java
  src/test/java/seedu/cc/testutil/TypicalPatients.java
Labels: FunctionalityBug

#187 Branch fix
  docs/UserGuide.md
  src/main/java/seedu/cc/logic/commands/appointmentcommands/AddPrescriptionCommand.java
Labels: priority.High

#194 Update UserGuide
  docs/UserGuide.md
Labels: type.documentation

#198 Branch dg
  docs/DeveloperGuide.md
Labels: PlannedEnhancements

#196 Branch fix and add my own ppp
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_sass/minima/initialize.scss
  docs/team/limjh2002.md
  docs/team/lyuanww.md
Labels: priority.High, DocumentationBug

#204 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddPrescriptionSequenceDiagram.puml
  docs/diagrams/ListAppointmentEventsSequenceDiagram.puml
  docs/diagrams/ListMedicalHistoryEventSequenceDiagram.puml
  docs/images/AddPrescriptionSequenceDiagram.png
  docs/images/ListAppointmentEventsSequenceDiagram.png
  docs/images/ListMedicalHistoryEventSequenceDiagram.png
Labels: type.documentation

#205 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.documentation

#203 Bk ppp
  docs/team/tanboonkhong.md
Labels: type.documentation
