Repository AY2324S1-CS2103T-F08-1/tp, pull requests merged in 2023-10, with the labels that each got.

#5 Edit about us page
  docs/AboutUs.md
  docs/images/limjh2002.png
Labels: type.documentation, priority.high

#6 Edit AboutUs Page
  docs/AboutUs.md
  docs/images/tanboonkhong.png
Labels: type.documentation, priority.high

#7 Edit About Us page for LiYuan
  docs/AboutUs.md
  docs/images/wongliyuan.png
Labels: type.documentation, priority.high

#8 Update README and Ui mock-up picture
  README.md
  docs/images/Ui.png
Labels: type.documentation, priority.high

#10 Create Boon Khong's PPP
  docs/team/tanboonkhong.md
Labels: type.documentation, priority.high

#11 Create pangyyen's PPP skeleton
  docs/team/pangyyen.md
Labels: type.documentation, priority.high

#13 Rename profile image for pangyyen
  docs/AboutUs.md
  docs/images/pangyyen.png
Labels: type.documentation, priority.high

#14 Rename image to GitHub username
  docs/AboutUs.md
  docs/images/lyuanww.png
Labels: priority.high

#18 Create new User Guide
  docs/UserGuide.md
Labels: type.documentation

#19 Create DG
  docs/DeveloperGuide.md
Labels: type.documentation

#20 Add in glossary in DG
  docs/DeveloperGuide.md
Labels: type.documentation

#22 Add delete command to user guide
  docs/UserGuide.md
Labels: type.documentation, priority.high

#24 Jh user guide
  docs/UserGuide.md
Labels: type.documentation, priority.high

#25 Update UserGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.high

#27 Update UserGuide to include UI image
  docs/UserGuide.md
Labels: type.documentation, priority.high

#28 Create jh-ppp
  docs/team/limjh2002.md
Labels: documentation

#36 Rename add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Task, priority.Medium, v1.2

#37 Change command to list-patient
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: type.Task, priority.Medium

#35 Rename "delete" command to "delete-patient"
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High, type.Task

#40 Rename "edit" command to "edit-patient"
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Task

#42 Add basic Patient class
  src/main/java/seedu/address/model/patient/Patient.java
  src/test/java/seedu/address/model/patient/PatientTest.java
Labels: priority.High

#43 Add Person Constructor and Nric Class
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, type.Task

#45 Branch add nric field
  src/main/java/seedu/cc/model/patient/Nric.java
  src/main/java/seedu/cc/model/patient/Patient.java
  src/test/java/seedu/cc/model/patient/NricTest.java
  src/test/java/seedu/cc/model/patient/PatientTest.java
  src/test/java/seedu/cc/model/person/NricTest.java
Labels: priority.High, type.Task

#46 Branch configure model
  src/main/java/seedu/cc/model/ClinicBook.java
  src/main/java/seedu/cc/model/NewModel.java
  src/main/java/seedu/cc/model/NewModelManager.java
  src/main/java/seedu/cc/model/NewReadOnlyUserPrefs.java
  src/main/java/seedu/cc/model/NewUserPrefs.java
  src/main/java/seedu/cc/model/ReadOnlyClinicBook.java
  src/main/java/seedu/cc/model/patient/Patient.java
  src/main/java/seedu/cc/model/patient/UniquePatientList.java
Labels: priority.High, type.Task

#51 Branch configure storage
  src/main/java/seedu/cc/storage/ClinicBookStorage.java
  src/main/java/seedu/cc/storage/ClinicStorage.java
  src/main/java/seedu/cc/storage/ClinicStorageManager.java
  src/main/java/seedu/cc/storage/JsonAdaptedPatient.java
  src/main/java/seedu/cc/storage/JsonClinicBookStorage.java
  src/main/java/seedu/cc/storage/JsonNewUserPrefsStorage.java
  src/main/java/seedu/cc/storage/JsonSerializableClinicBook.java
  src/main/java/seedu/cc/storage/NewUserPrefsStorage.java
Labels: type.Task, priority.Medium

#53 Branch configure model
  src/main/java/seedu/cc/model/patient/UniquePatientList.java
  src/main/java/seedu/cc/model/patient/exceptions/DuplicatePatientException.java
  src/main/java/seedu/cc/model/patient/exceptions/PatientNotFoundException.java
Labels: priority.High, type.Task

#55 Branch full port
  src/main/java/seedu/cc/MainApp.java
  src/main/java/seedu/cc/logic/ClinicLogicManager.java
  src/main/java/seedu/cc/logic/commands/AddPatientCommand.java
  src/main/java/seedu/cc/logic/commands/ClearPatientCommand.java
  src/main/java/seedu/cc/logic/commands/ClinicCommand.java
  src/main/java/seedu/cc/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/cc/logic/commands/EditPatientCommand.java
  src/main/java/seedu/cc/logic/commands/ExitClinicCommand.java
  src/main/java/seedu/cc/logic/commands/FindPatientCommand.java
  src/main/java/seedu/cc/logic/commands/HelpClinicCommand.java
  src/main/java/seedu/cc/logic/commands/ListPatientCommand.java
  src/main/java/seedu/cc/model/AddressBook.java
  src/main/java/seedu/cc/model/Model.java
  src/main/java/seedu/cc/model/ModelManager.java
  src/main/java/seedu/cc/model/NewModel.java
  src/main/java/seedu/cc/model/NewModelManager.java
  src/main/java/seedu/cc/model/NewReadOnlyUserPrefs.java
  src/main/java/seedu/cc/model/NewUserPrefs.java
  src/main/java/seedu/cc/model/ReadOnlyAddressBook.java
  src/main/java/seedu/cc/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/cc/model/UserPrefs.java
  src/main/java/seedu/cc/model/util/NewSampleDataUtil.java
  src/main/java/seedu/cc/model/util/SampleDataUtil.java
  src/main/java/seedu/cc/storage/ClinicStorage.java
  src/main/java/seedu/cc/storage/ClinicStorageManager.java
  src/main/java/seedu/cc/storage/JsonNewUserPrefsStorage.java
  src/main/java/seedu/cc/storage/NewUserPrefsStorage.java
Labels: priority.High

#56 Branch porting
  src/main/java/seedu/cc/MainApp.java
  src/main/java/seedu/cc/logic/ClinicLogicManager.java
  src/main/java/seedu/cc/storage/AddressBookStorage.java
  src/main/java/seedu/cc/storage/ClinicStorage.java
  src/main/java/seedu/cc/storage/ClinicStorageManager.java
  src/main/java/seedu/cc/storage/JsonNewUserPrefsStorage.java
  src/main/java/seedu/cc/storage/NewUserPrefsStorage.java
  src/main/java/seedu/cc/storage/Storage.java
  src/main/java/seedu/cc/storage/StorageManager.java
  src/main/java/seedu/cc/storage/UserPrefsStorage.java
Labels: priority.High

#82 Add Undo/Redo and Pharmacy Integration to DG
  docs/DeveloperGuide.md
Labels: type.documentation

#96 Branch UI
  src/main/java/seedu/cc/ui/PatientCard.java
  src/main/resources/images/AppointmentCardIcons/Time.png
  src/main/resources/images/MedicalHistoryCardIcons/Condition.png
  src/main/resources/images/MedicalHistoryCardIcons/Date.png
  src/main/resources/images/MedicalHistoryCardIcons/Treatment.png
  src/main/resources/images/PatientCardIcons/Address.png
  src/main/resources/images/PatientCardIcons/Age.png
  src/main/resources/images/PatientCardIcons/Alias.png
  src/main/resources/images/PatientCardIcons/NRIC.png
  src/main/resources/images/PatientCardIcons/Person.png
  src/main/resources/images/PatientCardIcons/Phone.png
  src/main/resources/view/AppointmentEventCard.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MedicalHistoryEventCard.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientListPanel.fxml
Labels: type.Enhancement, priority.Medium
